## View VS Copy

- View() it can modify the original data

- Copy() It can't modify the original data.

In [5]:
import numpy as np

In [12]:
# VIEW()

a = np.array([10,20,30,40,50,60,70,80])
b = a[2:5]
b[:] = 0
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [14]:
# COPY()

a = np.array([10,20,30,40,50,60,70,80])
b = a[2:5].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

## Reshaping the Data

In [20]:
# We know that 
# n(rows)*n(columns) = n(total_elements)
# if we have total_elements = 12
# 1*12, 12*1
# 2*6, 6*2
# 3*4, 4*3

# if we have total_elements = 36
# 1*36 , 36*1
# 2*18, 18*2
# 3*12, 12*3
# 4*9, 9*4
# 6*6



In [22]:
a = np.random.randint(1,50,12)
a

array([33,  4, 38,  9, 12, 15, 21, 13, 42,  5,  5, 43])

In [24]:
a.shape

(12,)

In [26]:
a.reshape(2,6)

array([[33,  4, 38,  9, 12, 15],
       [21, 13, 42,  5,  5, 43]])

In [28]:
a.reshape(6,2)

array([[33,  4],
       [38,  9],
       [12, 15],
       [21, 13],
       [42,  5],
       [ 5, 43]])

In [30]:
a.reshape(4,3)

array([[33,  4, 38],
       [ 9, 12, 15],
       [21, 13, 42],
       [ 5,  5, 43]])

In [32]:
a.reshape(3,4)

array([[33,  4, 38,  9],
       [12, 15, 21, 13],
       [42,  5,  5, 43]])

In [34]:
a.reshape(12,1)

array([[33],
       [ 4],
       [38],
       [ 9],
       [12],
       [15],
       [21],
       [13],
       [42],
       [ 5],
       [ 5],
       [43]])

In [36]:
a.reshape(1,12)

array([[33,  4, 38,  9, 12, 15, 21, 13, 42,  5,  5, 43]])

In [39]:
a = np.random.randint(1,100,72)
a

array([79, 26, 11, 24, 41, 79, 92, 34, 35, 29, 17, 53, 48, 53, 80, 73, 47,
       55, 70, 43, 21, 56, 38, 47, 98, 56, 36, 52,  6, 80, 85, 54, 11, 73,
       89,  2, 46, 73, 20,  8, 18, 93, 89, 41, 47, 75, 56, 44, 59, 51, 88,
       30, 80, 91,  8, 87, 26, 90,  8, 42, 19, 91, 49, 81, 61,  4, 92, 94,
       49,  2, 15, 78])

In [41]:
# 2,36
# 4,18
# 6,12
# 8,9

In [43]:
a.reshape(2,36)

array([[79, 26, 11, 24, 41, 79, 92, 34, 35, 29, 17, 53, 48, 53, 80, 73,
        47, 55, 70, 43, 21, 56, 38, 47, 98, 56, 36, 52,  6, 80, 85, 54,
        11, 73, 89,  2],
       [46, 73, 20,  8, 18, 93, 89, 41, 47, 75, 56, 44, 59, 51, 88, 30,
        80, 91,  8, 87, 26, 90,  8, 42, 19, 91, 49, 81, 61,  4, 92, 94,
        49,  2, 15, 78]])

In [45]:
a.reshape(4,18)

array([[79, 26, 11, 24, 41, 79, 92, 34, 35, 29, 17, 53, 48, 53, 80, 73,
        47, 55],
       [70, 43, 21, 56, 38, 47, 98, 56, 36, 52,  6, 80, 85, 54, 11, 73,
        89,  2],
       [46, 73, 20,  8, 18, 93, 89, 41, 47, 75, 56, 44, 59, 51, 88, 30,
        80, 91],
       [ 8, 87, 26, 90,  8, 42, 19, 91, 49, 81, 61,  4, 92, 94, 49,  2,
        15, 78]])

In [47]:
a.reshape(6,12)

array([[79, 26, 11, 24, 41, 79, 92, 34, 35, 29, 17, 53],
       [48, 53, 80, 73, 47, 55, 70, 43, 21, 56, 38, 47],
       [98, 56, 36, 52,  6, 80, 85, 54, 11, 73, 89,  2],
       [46, 73, 20,  8, 18, 93, 89, 41, 47, 75, 56, 44],
       [59, 51, 88, 30, 80, 91,  8, 87, 26, 90,  8, 42],
       [19, 91, 49, 81, 61,  4, 92, 94, 49,  2, 15, 78]])

In [51]:
a.reshape(12,6)

array([[79, 26, 11, 24, 41, 79],
       [92, 34, 35, 29, 17, 53],
       [48, 53, 80, 73, 47, 55],
       [70, 43, 21, 56, 38, 47],
       [98, 56, 36, 52,  6, 80],
       [85, 54, 11, 73, 89,  2],
       [46, 73, 20,  8, 18, 93],
       [89, 41, 47, 75, 56, 44],
       [59, 51, 88, 30, 80, 91],
       [ 8, 87, 26, 90,  8, 42],
       [19, 91, 49, 81, 61,  4],
       [92, 94, 49,  2, 15, 78]])

In [49]:
a.reshape(8,9)

array([[79, 26, 11, 24, 41, 79, 92, 34, 35],
       [29, 17, 53, 48, 53, 80, 73, 47, 55],
       [70, 43, 21, 56, 38, 47, 98, 56, 36],
       [52,  6, 80, 85, 54, 11, 73, 89,  2],
       [46, 73, 20,  8, 18, 93, 89, 41, 47],
       [75, 56, 44, 59, 51, 88, 30, 80, 91],
       [ 8, 87, 26, 90,  8, 42, 19, 91, 49],
       [81, 61,  4, 92, 94, 49,  2, 15, 78]])

In [53]:
a.reshape(9,8)

array([[79, 26, 11, 24, 41, 79, 92, 34],
       [35, 29, 17, 53, 48, 53, 80, 73],
       [47, 55, 70, 43, 21, 56, 38, 47],
       [98, 56, 36, 52,  6, 80, 85, 54],
       [11, 73, 89,  2, 46, 73, 20,  8],
       [18, 93, 89, 41, 47, 75, 56, 44],
       [59, 51, 88, 30, 80, 91,  8, 87],
       [26, 90,  8, 42, 19, 91, 49, 81],
       [61,  4, 92, 94, 49,  2, 15, 78]])

# Conditional Selection in Numpy

In [56]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [60]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [62]:
b = a> 10
a[b]

array([11, 12, 13, 14, 15])

In [64]:
c = a <= 10
a[c]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
a[a % 2 ==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [68]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
## Matrix addition, multiplication, subtraction

In [72]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [74]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [76]:
a + b 

array([[ 6,  8],
       [10, 12]])

In [78]:
a - b

array([[-4, -4],
       [-4, -4]])

In [84]:
a.dot(b)   # dot() used to multiply the numbers

array([[19, 22],
       [43, 50]])

In [87]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.sum(a)

45

In [93]:
# axis = 1 ===> Row wise total

np.sum(a, axis = 1)

array([ 6, 15, 24])

In [95]:
# axis = 0 ===> column wise total

np.sum(a, axis = 0)

array([12, 15, 18])

## Unique() ==> It will return unique values or eliminate duplicate values.

- It will return 3 array

- Unique values array

- Indexing of original value  (return_index = True)

- Returns frequency of each unique value   (return_counts = True)



In [102]:
a = np.array([1,2,2,2,3,4,3,2,3,3,3,5,4,6])
a

array([1, 2, 2, 2, 3, 4, 3, 2, 3, 3, 3, 5, 4, 6])

In [106]:
np.unique(a, return_index = True, return_counts = True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  5, 11, 13], dtype=int64),
 array([1, 4, 5, 2, 1, 1], dtype=int64))

##  LinSpace() ==> It will create an array in which difference of each value will be equal


In [113]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

### Stacking in Numpy

- 1] Hstack() ==> It will combined multiple arrays into horizontally.
- 2] Vstack() ==> It will combined multiple arrays into vertically.

In [117]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [130]:
# hstack()

np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [132]:
# vstack()

np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])